version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "09:00"
      timezone: Asia/Tokyo
  - package-ecosystem: docker
    directory: /build-env
    schedule:
      interval: weekly
      day: wednesday
      time: "09:00"
      timezone: Asia/Tokyo
  - package-ecosystem: docker
    directory: /simplecheck-env
    schedule:
      interval: weekly
      day: wednesday
      time: "09:00"
      timezone: Asia/Tokyo
