name: Build
on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/build.yml"
      - "**/Dockerfile"
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - build-env
          - simplecheck-env

    env:
      DOCKERFILE_DIR: ${{ matrix.dockerfile }}
      IMAGE_NAME: docker.pkg.github.com/kiksworks/docker-build-env/${{ matrix.dockerfile }}

    steps:
      - uses: actions/checkout@main

      - run: docker build --pull -t $IMAGE_NAME:latest $DOCKERFILE_DIR
        env:
          DOCKER_BUILDKIT: "1"

      - name: Push container images
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u "$USERNAME" --password-stdin <<< "$PASSWORD"

          tag=$(date -u +%Y%m%d)
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$tag
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$tag

          rm -rf ~/.docker
