name: Build
on:
  push:
    branches: [master]
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker.pkg.github.com/kiksworks/docker-build-env/build-env

    steps:
      - uses: actions/checkout@v2

      - run: docker build --pull -t $IMAGE_NAME:latest .

      - name: Push container images
        env:
          USERNAME: $GITHUB_ACTOR
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u "$USERNAME" --password-stdin <<< "$PASSWORD"

          tag=$(date -u +%Y%m%d)
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$tag
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$tag

          rm -rf ~/.docker
