on:
  workflow_call:
    inputs:
      push:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        context:
          - build-env
          - simplecheck-env

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.context }}
      cancel-in-progress: true

    steps:
      - uses: docker/setup-buildx-action@v3.11.0
      - uses: docker/login-action@v3.4.0
        if: ${{ inputs.push }}
        id: login
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6.18.0
        with:
          tags: ghcr.io/kiksworks/${{ matrix.context }}:latest
          context: '{{defaultContext}}:${{ matrix.context }}'
          push: ${{ steps.login.outcome == 'success' }}
