name: Build
on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/build.yml"
      - "**/Dockerfile"
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - build-env
          - simplecheck-env

    env:
      DOCKERFILE_DIR: ${{ matrix.dockerfile }}
      IMAGE_NAME: kiksworks/${{ matrix.dockerfile }}

    steps:
      - uses: actions/checkout@main

      - run: docker build --pull -t "$IMAGE_NAME" "$DOCKERFILE_DIR"
        env:
          DOCKER_BUILDKIT: "1"

      - name: Push container images
        env:
          REGISTRY: ghcr.io
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login "$REGISTRY" -u "$USERNAME" --password-stdin <<< "$PASSWORD"

          tag=$(date -u +%Y%m%d)
          docker tag "$IMAGE_NAME" "$REGISTRY/$IMAGE_NAME:$tag"
          docker push "$REGISTRY/$IMAGE_NAME:$tag"
          docker tag "$IMAGE_NAME" "$REGISTRY/$IMAGE_NAME:latest"
          docker push "$REGISTRY/$IMAGE_NAME:latest"

          rm -rf ~/.docker
